version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install sphinx sphinx-rtd-theme
    - cd docs && sphinx-apidoc -o api -e -f ../pandahandler
    - cd docs && sphinx-build -b html . $READTHEDOCS_OUTPUT/html

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
