version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install sphinx sphinx-rtd-theme
    - cd docs && sphinx-apidoc -o api -e -f ../pandahandler

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
