version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - sphinx-apidoc -o docs/api pandahandler -f

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
